title: Lukas Rosenberger
position: Assistant Professor 
affiliation: LMU Munich
#email: lukas.rosenberger@econ.lmu.de
keywords: Lukas Rosenberger Econ Economics History Northwestern University LMU Munich Universität Ludwig Maximilians
google_scholar: https://scholar.google.com/citations?user=LjI69LwAAAAJ&hl=de&oi=ao
#github_link: https://github.com/yaoyao-liu/minimal-light
avatar: ./assets/img/Lukas_Rosenberger_LMU.jpg
#google_analytics: UA-111540567-4
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png
description: Lukas Rosenberger | Assistant Professor at LMU Munich. Economist, Economic Historian
#canonical: 
external_theme: yaoyao-liu/minimal-light
