title: Lukas Rosenberger
position: Postdoctoral Scholar
affiliation: Northwestern University
#email: lukas.rosenberger@econ.lmu.de
keywords: Lukas Rosenberger Northwestern University LMU Munich Universität
#google_scholar: https://scholar.google.com/
#github_link: https://github.com/yaoyao-liu/minimal-light
avatar: ./assets/img/Lukas_Rosenberger_LMU.jpg
#google_analytics: UA-111540567-4
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png
description: Lukas Rosenberger | Postdoctoral scholar at Northwestern University. Economist and Economic Historian
#canonical: 
theme: minimal-light
